"""empty message

Revision ID: ed43b17e480f
Revises: 
Create Date: 2024-02-19 23:09:57.417568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed43b17e480f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('role_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id_fk', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('passwd', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id_fk'], ['user_roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('board',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('board_name', sa.String(length=20), nullable=False),
    sa.Column('board_owner_fk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['board_owner_fk'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('board_id')
    )
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('otp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expire_in', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expire_in', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expire_in', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board_list',
    sa.Column('board_list_id', sa.Integer(), nullable=False),
    sa.Column('board_id_fk', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(length=20), nullable=False),
    sa.Column('list_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id_fk'], ['board.board_id'], ),
    sa.PrimaryKeyConstraint('board_list_id')
    )
    op.create_table('board_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_fk', sa.Integer(), nullable=False),
    sa.Column('board_id_fk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id_fk'], ['board.board_id'], ),
    sa.ForeignKeyConstraint(['member_fk'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=20), nullable=False),
    sa.Column('task_description', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('board_id_fk', sa.Integer(), nullable=False),
    sa.Column('board_list_fk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['board_id_fk'], ['board.board_id'], ),
    sa.ForeignKeyConstraint(['board_list_fk'], ['board_list.board_list_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('sub_tasks',
    sa.Column('sub_task_id', sa.Integer(), nullable=False),
    sa.Column('parent_task', sa.Integer(), nullable=False),
    sa.Column('sub_task_description', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('is_check', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['parent_task'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('sub_task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_tasks')
    op.drop_table('tasks')
    op.drop_table('board_members')
    op.drop_table('board_list')
    op.drop_table('user_verification')
    op.drop_table('password_reset')
    op.drop_table('otp')
    op.drop_table('board')
    op.drop_table('users')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
